time_varying_parameter:
  'n_ki_multiplier': 17
  'n_dSys_change': 8
  'n_d_Sym_P_As_change': 8
  'n_frac_crit_change': 10
  'n_fraction_dead_change': 9
  'n_recovery_time_crit_change': 2
  'n_recovery_time_hosp_change': 1
interventions:
  'n_gradual_steps': 8 # if not using a csv and if scaleup date < 2099 in master yaml
  'trigger_channel': 'crit_det'
  'bvariant_csv': ""
  'vaccination_csv': "vaccination_linearpast30days_cap.csv" #"vaccination_linear_doubled.csv" "vaccination_linear.csv" vaccination_linearpast30days.csv
  'reopen_relative_to_initial': False
  'reopen_regionspecific': False
  'reopen_csv': ""
  'rollback_regionspecific': False
  'rollback_csv': ""
